# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AZeo3l4mQ1rGm6AeEYQlUCB1wGRNWSS8
"""

from google.colab import drive
import os

drive.mount('/content/drive/', force_remount=True)

# Change the path to the current working directory
os.chdir(r'/content/drive/MyDrive/Cover_letters/Reviews')

!ls



"""# 1.0 The Effect of Imputation

### Mean vs Median in Data Distribution
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

np.random.seed(123)  # reproducible results
dates = pd.date_range("2000-01-01", periods=500, freq="D")

# ============================================================
# GENERATE SYMMETRIC DATA (NORMAL, NO OUTLIERS)
# ============================================================
n = 500
# Purely normal distribution – symmetric, no outliers
values = np.random.normal(loc=50, scale=10, size=n)  # mean=50, std=10

# Add 25% random missing values (similar proportion as before)
missing = np.random.choice([True, False], size=n, p=[0.45, 0.55])
df = pd.DataFrame({"date": dates, "original": values})
df["with_missing"] = df["original"].where(~missing, np.nan)

# ============================================================
# IMPUTATION: MEAN vs MEDIAN
# ============================================================
mean_val = df["with_missing"].mean()
median_val = df["with_missing"].median()
df["mean_imp"] = df["with_missing"].fillna(mean_val)
df["median_imp"] = df["with_missing"].fillna(median_val)

# For symmetric data, we don't have outliers; "bulk" means all points
mask_missing = df["with_missing"].isna()

# Errors on ALL missing points
rmse_mean_all = np.sqrt(((df.loc[mask_missing, "original"] - mean_val)**2).mean())
rmse_median_all = np.sqrt(((df.loc[mask_missing, "original"] - median_val)**2).mean())

# Also compute errors on "bulk" = all missing (no outlier separation needed)
# But we keep the same variable names for consistency
bulk_missing = mask_missing  # all missing are "bulk"
rmse_mean_bulk = rmse_mean_all
rmse_median_bulk = rmse_median_all
ratio = rmse_mean_bulk / rmse_median_bulk

# ============================================================
# PRINT RESULTS
# ============================================================
print("="*60)
print("DATA: Symmetric (Normal) – no outliers")
print("="*60)
print(f"Mean of observed data = {mean_val:.2f}")
print(f"Median of observed data = {median_val:.2f}")
print(f"(Mean and median are nearly equal – distribution symmetric)")
print(f"\n--- All missing points ---")
print(f"RMSE mean imputation   = {rmse_mean_all:.2f}")
print(f"RMSE median imputation = {rmse_median_all:.2f}")
if ratio < 1:
    print(f"\n→ Mean imputation error is {1/ratio:.1f}x smaller than median.")
elif ratio > 1:
    print(f"\n→ Median imputation error is {ratio:.1f}x smaller than mean.")
else:
    print("\n→ Both methods perform identically.")
print("\n** For symmetric data, mean imputation works well (low error). **")

# ============================================================
# PLOT 1: FULL TIME SERIES
# ============================================================
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 8))

ax1.plot(df["date"], df["original"], alpha=0.4, label="Original (complete)")
ax1.plot(df["date"], df["mean_imp"], 'r--', label=f"Mean imputed (={mean_val:.1f})", alpha=0.7)
ax1.plot(df["date"], df["median_imp"], 'g--', label=f"Median imputed (={median_val:.1f})", alpha=0.7)
ax1.set_ylabel("Value")
ax1.set_title("Symmetric Data: Mean and median imputation are nearly identical")
ax1.legend()
ax1.grid(True, alpha=0.3)

# ============================================================
# PLOT 2: ZOOM ON FIRST 100 POINTS
# ============================================================
first_100 = df.iloc[:100]
missing_first100 = mask_missing.iloc[:100]

ax2.plot(first_100["date"], first_100["original"], alpha=0.6, label="Original")
ax2.plot(first_100["date"], first_100["mean_imp"], 'r--', alpha=0.7, label="Mean imputed")
ax2.plot(first_100["date"], first_100["median_imp"], 'g--', alpha=0.7, label="Median imputed")

# Highlight imputed points
ax2.scatter(first_100.loc[missing_first100, "date"],
            first_100.loc[missing_first100, "mean_imp"],
            color='red', s=40, zorder=5, label="Mean‑imputed points")
ax2.scatter(first_100.loc[missing_first100, "date"],
            first_100.loc[missing_first100, "median_imp"],
            color='green', s=40, zorder=5, marker='x', label="Median‑imputed points")

ax2.set_ylabel("Value")
ax2.set_title("Zoom: both methods impute near the true data cloud")
ax2.legend()
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# ============================================================
# PLOT 3: DISTRIBUTION (HISTOGRAM)
# ============================================================
plt.figure(figsize=(8,4))
plt.hist(df["original"], bins=30, alpha=0.5, label="Original", density=True)
plt.axvline(mean_val, color='red', linestyle='--', linewidth=2, label=f"Mean = {mean_val:.1f}")
plt.axvline(median_val, color='green', linestyle='--', linewidth=2, label=f"Median = {median_val:.1f}")
plt.xlabel("Value")
plt.title("Symmetric distribution: mean ≈ median")
plt.legend()
plt.show()





import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

np.random.seed(123)  # reproducible results
dates = pd.date_range("2000-01-01", periods=500, freq="D")

# ============================================================
# GENERATE DATA: BULK (normal) + OUTLIERS (far away)
# ============================================================
n = 500
n_outliers = int(0.1 * n)  # 10% extreme outliers
values = np.concatenate([
    np.random.normal(0, 1, n - n_outliers),   # bulk around 0
    np.random.normal(100, 1, n_outliers)      # outliers around 100
])
np.random.shuffle(values)

# Add 15% random missing values
missing = np.random.choice([True, False], size=n, p=[0.25, 0.75])
df = pd.DataFrame({"date": dates, "original": values})
df["with_missing"] = df["original"].where(~missing, np.nan)

# ============================================================
# IMPUTATION: MEAN vs MEDIAN
# ============================================================
mean_val = df["with_missing"].mean()
median_val = df["with_missing"].median()
df["mean_imp"] = df["with_missing"].fillna(mean_val)
df["median_imp"] = df["with_missing"].fillna(median_val)

# Identify which missing positions are "bulk" (non‑outlier)
mask_missing = df["with_missing"].isna()
is_outlier_original = df["original"] > 5   # threshold separates bulk from outliers

# Errors on ALL missing points
rmse_mean_all = np.sqrt(((df.loc[mask_missing, "original"] - mean_val)**2).mean())
rmse_median_all = np.sqrt(((df.loc[mask_missing, "original"] - median_val)**2).mean())

# Errors on BULK missing points only (the typical data)
bulk_missing = mask_missing & ~is_outlier_original
if bulk_missing.any():
    rmse_mean_bulk = np.sqrt(((df.loc[bulk_missing, "original"] - mean_val)**2).mean())
    rmse_median_bulk = np.sqrt(((df.loc[bulk_missing, "original"] - median_val)**2).mean())
    ratio = rmse_mean_bulk / rmse_median_bulk
else:
    rmse_mean_bulk = rmse_median_bulk = ratio = np.nan

# ============================================================
# PRINT RESULTS
# ============================================================
print("="*60)
print("DATA: bulk ~ N(0,1), outliers ~ N(100,1) (10% outliers)")
print("="*60)
print(f"Mean of observed data = {mean_val:.2f}")
print(f"Median of observed data = {median_val:.2f}")
print(f"\n--- All missing points ---")
print(f"RMSE mean imputation   = {rmse_mean_all:.2f}")
print(f"RMSE median imputation = {rmse_median_all:.2f}")
print(f"\n--- BULK missing points (non‑outliers) ONLY ---")
print(f"RMSE mean imputation   = {rmse_mean_bulk:.2f}")
print(f"RMSE median imputation = {rmse_median_bulk:.2f}")
if not np.isnan(ratio):
    print(f"\n→ For the typical data, median imputation error is {ratio:.1f}x smaller!")
else:
    print("\n→ No bulk missing points to evaluate.")

# ============================================================
# PLOT 1: FULL TIME SERIES
# ============================================================
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 8))

ax1.plot(df["date"], df["original"], alpha=0.4, label="Original (complete)")
ax1.plot(df["date"], df["mean_imp"], 'r--', label=f"Mean imputed (={mean_val:.1f})", alpha=0.7)
ax1.plot(df["date"], df["median_imp"], 'g--', label=f"Median imputed (={median_val:.1f})", alpha=0.7)
ax1.set_ylabel("Value")
ax1.set_title("Mean imputation inserts a value near 10, but most data are near 0")
ax1.legend()
ax1.grid(True, alpha=0.3)

# ============================================================
# PLOT 2: ZOOM ON FIRST 100 POINTS
# ============================================================
first_100 = df.iloc[:100]
missing_first100 = mask_missing.iloc[:100]

ax2.plot(first_100["date"], first_100["original"], alpha=0.6, label="Original")
ax2.plot(first_100["date"], first_100["mean_imp"], 'r--', alpha=0.7, label="Mean imputed")
ax2.plot(first_100["date"], first_100["median_imp"], 'g--', alpha=0.7, label="Median imputed")

# Highlight imputed points
ax2.scatter(first_100.loc[missing_first100, "date"],
            first_100.loc[missing_first100, "mean_imp"],
            color='red', s=40, zorder=5, label="Mean‑imputed points")
ax2.scatter(first_100.loc[missing_first100, "date"],
            first_100.loc[missing_first100, "median_imp"],
            color='green', s=40, zorder=5, marker='x', label="Median‑imputed points")

ax2.set_ylabel("Value")
ax2.set_title("Zoom: mean imputation gives ~10 (red dots), median gives ~0 (green x's)")
ax2.legend()
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# ============================================================
# PLOT 3: DISTRIBUTION
# ============================================================
plt.figure(figsize=(8,4))
plt.hist(df["original"], bins=50, alpha=0.5, label="Original", density=True)
plt.axvline(mean_val, color='red', linestyle='--', linewidth=2, label=f"Mean = {mean_val:.1f}")
plt.axvline(median_val, color='green', linestyle='--', linewidth=2, label=f"Median = {median_val:.1f}")
plt.xlabel("Value")
plt.title("Distribution: mean is pulled toward outliers (right tail)")
plt.legend()
plt.show()

"""* Mean gets pulled by outliers
* Median resistant to outliers

When:
* Right-skewed: Mean > Median
* Left-skwed: Mean < Median
* Symmetric: Mean $\approx$ Median
"""





# ============================================================
# BLOCK 1
# GENERATE TIME SERIES WITH LONG CONTINUOUS MISSING GAP
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

np.random.seed(42)

# ------------------------------------------------------------
# GENERATE TIME SERIES
# ------------------------------------------------------------

n = 500

dates = pd.date_range(
    start="1980-01-01",
    periods=n,
    freq="M"
)

t = np.arange(n)

# Trend + seasonality + noise

signal = (
    50
    + 0.05*t
    + 10*np.sin(2*np.pi*t/12)
    + np.random.normal(0, 2, n)
)

df = pd.DataFrame({
    "date": dates,
    "temp": signal
})

# ------------------------------------------------------------
# CREATE LONG CONTINUOUS GAP
# ------------------------------------------------------------

missing_start = 80
missing_end = 160

df_missing = df.copy()

df_missing.loc[
    missing_start:missing_end,
    "temp"
] = np.nan

# ------------------------------------------------------------
# VISUALIZE MISSING GAP
# ------------------------------------------------------------

plt.figure(figsize=(15,5))

# Observed data only
plt.plot(
    df_missing["date"],
    df_missing["temp"],
    color="black",
    linewidth=2,
    label="Observed Data"
)

# Highlight gap
plt.axvspan(
    df["date"][missing_start],
    df["date"][missing_end],
    color="red",
    alpha=0.2,
    label="Missing Gap"
)

plt.legend()

plt.title("Time Series with Long Continuous Missing Gap")

plt.xlabel("Date")
plt.ylabel("Temperature")

plt.show()



# ============================================================
# BLOCK 2
# MEAN, MEDIAN, LINEAR INTERPOLATION
# ============================================================

from sklearn.metrics import mean_squared_error

# ------------------------------------------------------------
# TRUE HIDDEN VALUES
# ------------------------------------------------------------

true_values = df.loc[
    missing_start:missing_end,
    "temp"
]

# ============================================================
# A. MEAN IMPUTATION
# ============================================================

df_mean = df_missing.copy()

mean_value = df_mean["temp"].mean()

df_mean["mean_imputed"] = (
    df_mean["temp"]
    .fillna(mean_value)
)

# ============================================================
# B. MEDIAN IMPUTATION
# ============================================================

df_median = df_missing.copy()

median_value = df_median["temp"].median()

df_median["median_imputed"] = (
    df_median["temp"]
    .fillna(median_value)
)

# ============================================================
# C. LINEAR INTERPOLATION
# ============================================================

df_linear = df_missing.copy()

df_linear["linear_interp"] = (
    df_linear["temp"]
    .interpolate(method="linear")
)

# ============================================================
# RMSE COMPARISON
# ============================================================

mean_rmse = np.sqrt(
    mean_squared_error(
        true_values,
        df_mean.loc[
            missing_start:missing_end,
            "mean_imputed"
        ]
    )
)

median_rmse = np.sqrt(
    mean_squared_error(
        true_values,
        df_median.loc[
            missing_start:missing_end,
            "median_imputed"
        ]
    )
)

linear_rmse = np.sqrt(
    mean_squared_error(
        true_values,
        df_linear.loc[
            missing_start:missing_end,
            "linear_interp"
        ]
    )
)

print("\nRMSE VALUES\n")

print(f"Mean Imputation   : {mean_rmse:.3f}")
print(f"Median Imputation : {median_rmse:.3f}")
print(f"Linear Interp     : {linear_rmse:.3f}")

# ============================================================
# VISUALIZATION
# ============================================================

plt.figure(figsize=(16,6))

# Observed data
plt.plot(
    df_missing["date"],
    df_missing["temp"],
    color="black",
    linewidth=2,
    label="Observed Data"
)

# True hidden signal
plt.plot(
    df.loc[
        missing_start:missing_end,
        "date"
    ],
    true_values,
    color="blue",
    linewidth=3,
    label="True Hidden Signal"
)

# Mean
plt.plot(
    df_mean["date"],
    df_mean["mean_imputed"],
    label="Mean Imputation"
)

# Median
plt.plot(
    df_median["date"],
    df_median["median_imputed"],
    label="Median Imputation"
)

# Linear
plt.plot(
    df_linear["date"],
    df_linear["linear_interp"],
    label="Linear Interpolation"
)

# Missing region
plt.axvspan(
    df["date"][missing_start],
    df["date"][missing_end],
    color="red",
    alpha=0.1
)

plt.legend()

plt.title("Mean, Median and Linear Interpolation")

plt.xlabel("Date")
plt.ylabel("Temperature")

plt.show()



# ============================================================
# BLOCK 2 (Improved Imputation)
# ============================================================

from sklearn.linear_model import LinearRegression

# ------------------------------------------------------------
# Prepare training data (non‑missing indices)
# ------------------------------------------------------------
train_mask = df_missing["temp"].notna().values
t_train = t[train_mask].reshape(-1, 1)
y_train = df_missing.loc[train_mask, "temp"].values

# ------------------------------------------------------------
# Build Fourier features
# ------------------------------------------------------------
def fourier_features(t_vals, period=12, n_harmonics=2):
    features = []
    for k in range(1, n_harmonics + 1):
        features.append(np.sin(2 * np.pi * k * t_vals / period))
        features.append(np.cos(2 * np.pi * k * t_vals / period))
    return np.column_stack(features)

X_train = np.column_stack([
    t_train,
    fourier_features(t_train.ravel())
])

# ------------------------------------------------------------
# Fit model
# ------------------------------------------------------------
model = LinearRegression()
model.fit(X_train, y_train)

# ------------------------------------------------------------
# Predict missing gap
# ------------------------------------------------------------
missing_indices = list(range(missing_start, missing_end + 1))   # explicit list
t_missing = t[missing_indices].reshape(-1, 1)
X_missing = np.column_stack([
    t_missing,
    fourier_features(t_missing.ravel())
])
y_pred = model.predict(X_missing)   # 1D array, length = len(missing_indices)

# ------------------------------------------------------------
# Reconstruct
# ------------------------------------------------------------
df_reconstructed = df_missing.copy()
df_reconstructed.iloc[missing_indices, df_reconstructed.columns.get_loc("temp")] = y_pred

# ------------------------------------------------------------
# Plot
# ------------------------------------------------------------
plt.figure(figsize=(15,5))
plt.plot(df["date"], df["temp"], color="blue", linewidth=1.5, alpha=0.7, label="Original (complete)")
plt.plot(df_reconstructed["date"].iloc[missing_indices], y_pred,
         color="red", linewidth=2, linestyle="--", label="Reconstructed gap")
plt.plot(df_missing["date"], df_missing["temp"], color="black", linewidth=1, alpha=0.5, label="Observed (with gap)")
plt.axvspan(df["date"].iloc[missing_start], df["date"].iloc[missing_end],
            color="gray", alpha=0.2, label="Missing region")
plt.legend()
plt.title("Long Missing Gap Reconstruction (Trend + Fourier Regression)")
plt.xlabel("Date")
plt.ylabel("Temperature")
plt.show()

# Optional error check
from sklearn.metrics import mean_absolute_error
y_true = df.iloc[missing_indices]["temp"].values
mae = mean_absolute_error(y_true, y_pred)
print(f"Mean Absolute Error over the missing gap: {mae:.2f}")

"""* doubling the missing gap"""

# ============================================================
# BLOCK 1: Generate time series (same as before)
# ============================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

sns.set(style="whitegrid")
np.random.seed(42)

n = 500
dates = pd.date_range(start="1980-01-01", periods=n, freq="M")
t = np.arange(n)

signal = 50 + 0.05*t + 10*np.sin(2*np.pi*t/12) + np.random.normal(0, 2, n)
df = pd.DataFrame({"date": dates, "temp": signal})

# ============================================================
# DOUBLE THE MISSING GAP LENGTH (now 160 months)
# ============================================================
missing_start = 80
missing_end = 239   # was 160 -> now 80 + 160 - 1 = 239 (160 months long)

df_missing = df.copy()
df_missing.loc[missing_start:missing_end, "temp"] = np.nan

# ============================================================
# RECONSTRUCTION USING TREND + FOURIER REGRESSION
# ============================================================
train_mask = df_missing["temp"].notna().values
t_train = t[train_mask].reshape(-1, 1)
y_train = df_missing.loc[train_mask, "temp"].values

def fourier_features(t_vals, period=12, n_harmonics=2):
    features = []
    for k in range(1, n_harmonics+1):
        features.append(np.sin(2*np.pi*k*t_vals/period))
        features.append(np.cos(2*np.pi*k*t_vals/period))
    return np.column_stack(features)

X_train = np.column_stack([t_train, fourier_features(t_train.ravel())])
model = LinearRegression().fit(X_train, y_train)

missing_indices = list(range(missing_start, missing_end+1))
t_missing = t[missing_indices].reshape(-1,1)
X_missing = np.column_stack([t_missing, fourier_features(t_missing.ravel())])
y_pred = model.predict(X_missing)

df_reconstructed = df_missing.copy()
col_idx = df_reconstructed.columns.get_loc("temp")
df_reconstructed.iloc[missing_indices, col_idx] = y_pred

# ============================================================
# PLOT: Original vs. reconstructed (doubled gap)
# ============================================================
plt.figure(figsize=(15,5))
plt.plot(df["date"], df["temp"], color="blue", linewidth=1.5, alpha=0.7, label="Original (complete)")
plt.plot(df_reconstructed["date"].iloc[missing_indices], y_pred,
         color="red", linewidth=2, linestyle="--", label="Reconstructed gap")
plt.plot(df_missing["date"], df_missing["temp"], color="black", linewidth=1, alpha=0.5, label="Observed (with gap)")
plt.axvspan(df["date"].iloc[missing_start], df["date"].iloc[missing_end],
            color="gray", alpha=0.2, label=f"Missing region ({len(missing_indices)} months)")
plt.legend()
plt.title("Doubled Missing Gap Reconstruction (160 months)")
plt.xlabel("Date")
plt.ylabel("Temperature")
plt.show()

y_true = df.iloc[missing_indices]["temp"].values
mae = mean_absolute_error(y_true, y_pred)
print(f"Mean Absolute Error over the {len(missing_indices)}-month gap: {mae:.2f}")



"""triple missing gaps"""

missing_start = 80
missing_end = 322   # triple gap (243 months)

df_missing = df.copy()
df_missing.loc[missing_start:missing_end, "temp"] = np.nan

# Train on observed data
train_mask = df_missing["temp"].notna().values
t_train = t[train_mask].reshape(-1, 1)
y_train = df_missing.loc[train_mask, "temp"].values

def fourier_features(t_vals, period=12, n_harmonics=2):
    features = []
    for k in range(1, n_harmonics+1):
        features.append(np.sin(2*np.pi*k*t_vals/period))
        features.append(np.cos(2*np.pi*k*t_vals/period))
    return np.column_stack(features)

X_train = np.column_stack([t_train, fourier_features(t_train.ravel())])
model = LinearRegression().fit(X_train, y_train)

missing_indices = list(range(missing_start, missing_end+1))
t_missing = t[missing_indices].reshape(-1,1)
X_missing = np.column_stack([t_missing, fourier_features(t_missing.ravel())])
y_pred = model.predict(X_missing)

df_reconstructed = df_missing.copy()
col_idx = df_reconstructed.columns.get_loc("temp")
df_reconstructed.iloc[missing_indices, col_idx] = y_pred

# Plot
plt.figure(figsize=(15,5))
plt.plot(df["date"], df["temp"], color="blue", linewidth=1.5, alpha=0.7, label="Original")
plt.plot(df_reconstructed["date"].iloc[missing_indices], y_pred,
         color="red", linewidth=2, linestyle="--", label="Reconstructed gap")
plt.plot(df_missing["date"], df_missing["temp"], color="black", linewidth=1, alpha=0.5, label="Observed (with gap)")
plt.axvspan(df["date"].iloc[missing_start], df["date"].iloc[missing_end],
            color="gray", alpha=0.2, label=f"Missing ({len(missing_indices)} months)")
plt.legend()
plt.title("Triple Missing Gap Reconstruction (243 months)")
plt.xlabel("Date")
plt.ylabel("Temperature")
plt.show()

from sklearn.metrics import mean_absolute_error
y_true = df.iloc[missing_indices]["temp"].values
mae = mean_absolute_error(y_true, y_pred)
print(f"MAE over {len(missing_indices)}-month gap: {mae:.2f}")



"""RANDOM MISSING GAPS + RECONSTRUCTION"""

# ============================================================
# FULL SCRIPT: 3 RANDOM MISSING GAPS + RECONSTRUCTION
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

# ------------------------------------------------------------
# 1. Generate synthetic time series (trend + seasonality + noise)
# ------------------------------------------------------------
sns.set(style="whitegrid")
np.random.seed(42)          # reproducible series and gaps

n = 500
dates = pd.date_range(start="1980-01-01", periods=n, freq="M")
t = np.arange(n)

signal = (
    50
    + 0.05 * t
    + 10 * np.sin(2 * np.pi * t / 12)
    + np.random.normal(0, 2, n)
)

df = pd.DataFrame({"date": dates, "temp": signal})

# ------------------------------------------------------------
# 2. Create three random non‑overlapping missing gaps
# ------------------------------------------------------------
def random_non_overlapping_gaps(n_points, n_gaps=3, min_len=15, max_len=50, random_state=42):
    rng = np.random.RandomState(random_state)
    gaps = []
    attempts = 0
    while len(gaps) < n_gaps and attempts < 1000:
        start = rng.randint(50, n_points - max_len - 10)
        length = rng.randint(min_len, max_len + 1)
        end = start + length - 1
        new_gap = set(range(start, end + 1))
        # avoid overlapping with previous gaps
        if not any(new_gap.intersection(set(range(s, e+1))) for (s, e) in gaps):
            gaps.append((start, end))
        attempts += 1
    return gaps

gap_intervals = random_non_overlapping_gaps(n, n_gaps=3)
print("Generated gaps (start, end) with lengths:")
for i, (s, e) in enumerate(gap_intervals):
    print(f"  Gap {i+1}: months {s}–{e} (length {e-s+1})")

# ------------------------------------------------------------
# 3. Apply missing gaps to the dataframe
# ------------------------------------------------------------
df_missing = df.copy()
all_missing_indices = []
for start, end in gap_intervals:
    df_missing.loc[start:end, "temp"] = np.nan
    all_missing_indices.extend(range(start, end + 1))
all_missing_indices = sorted(all_missing_indices)

# ------------------------------------------------------------
# 4. Define Fourier features (trend + seasonal harmonics)
# ------------------------------------------------------------
def fourier_features(t_vals, period=12, n_harmonics=2):
    features = []
    for k in range(1, n_harmonics + 1):
        features.append(np.sin(2 * np.pi * k * t_vals / period))
        features.append(np.cos(2 * np.pi * k * t_vals / period))
    return np.column_stack(features)

# ------------------------------------------------------------
# 5. Train the model on all observed (non‑missing) data
# ------------------------------------------------------------
train_mask = df_missing["temp"].notna().values
t_train = t[train_mask].reshape(-1, 1)
y_train = df_missing.loc[train_mask, "temp"].values

X_train = np.column_stack([
    t_train,
    fourier_features(t_train.ravel())
])

model = LinearRegression()
model.fit(X_train, y_train)

# ------------------------------------------------------------
# 6. Predict all missing values
# ------------------------------------------------------------
t_missing = t[all_missing_indices].reshape(-1, 1)
X_missing = np.column_stack([
    t_missing,
    fourier_features(t_missing.ravel())
])
y_pred = model.predict(X_missing)   # shape: (total missing points,)

# ------------------------------------------------------------
# 7. Reconstruct the dataframe (for convenience)
# ------------------------------------------------------------
df_reconstructed = df_missing.copy()
col_idx = df_reconstructed.columns.get_loc("temp")
df_reconstructed.iloc[all_missing_indices, col_idx] = y_pred

# ------------------------------------------------------------
# 8. Plot: each missing gap separately (no connecting lines)
# ------------------------------------------------------------
plt.figure(figsize=(15, 5))

# Original complete series
plt.plot(df["date"], df["temp"], color="blue", linewidth=1.5, alpha=0.7, label="Original (complete)")

# Observed data (with gaps)
plt.plot(df_missing["date"], df_missing["temp"], color="black", linewidth=1, alpha=0.5, label="Observed (with gaps)")

# Reconstruct each gap individually
for start, end in gap_intervals:
    gap_indices = list(range(start, end + 1))
    # locate these indices inside the flattened y_pred
    start_pos = all_missing_indices.index(start)
    end_pos = all_missing_indices.index(end) + 1
    y_pred_gap = y_pred[start_pos:end_pos]

    plt.plot(df_reconstructed["date"].iloc[gap_indices], y_pred_gap,
             color="red", linewidth=2, linestyle="--")

# Highlight missing regions (shaded areas)
for start, end in gap_intervals:
    plt.axvspan(df["date"].iloc[start], df["date"].iloc[end],
                color="gray", alpha=0.2, label="_nolegend_")

plt.legend(["Original (complete)", "Observed (with gaps)", "Reconstructed gaps"])
plt.title("Reconstruction of 3 Random Missing Gaps (no lines between gaps)")
plt.xlabel("Date")
plt.ylabel("Temperature")
plt.show()

# ------------------------------------------------------------
# 9. Evaluation: MAE per gap and total
# ------------------------------------------------------------
print("\nReconstruction errors:")
for i, (start, end) in enumerate(gap_intervals):
    y_true_gap = df.iloc[start:end+1]["temp"].values
    start_pos = all_missing_indices.index(start)
    end_pos = all_missing_indices.index(end) + 1
    y_pred_gap = y_pred[start_pos:end_pos]
    mae = mean_absolute_error(y_true_gap, y_pred_gap)
    print(f"  Gap {i+1} (length {end-start+1}): MAE = {mae:.2f}")

total_mae = mean_absolute_error(df.iloc[all_missing_indices]["temp"].values, y_pred)
print(f"  Total over {len(all_missing_indices)} missing points: MAE = {total_mae:.2f}")





import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import Ridge, RidgeCV
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score

from yellowbrick.regressor import ResidualsPlot

# ============================================================
# SIMULATED DATASET
# PURPOSE:
# Demonstrate why feature scaling matters for Ridge regression
# ============================================================

np.random.seed(42)

n_samples = 1200

# ------------------------------------------------------------
# FEATURES WITH VERY DIFFERENT SCALES
# ------------------------------------------------------------

X1 = np.random.normal(0, 1, n_samples)            # scale ~ 1
X2 = np.random.normal(0, 5000, n_samples)         # scale ~ 5000
X3 = np.random.normal(0, 0.0005, n_samples)       # scale ~ 0.0005
X4 = X1 * 0.98 + np.random.normal(0, 0.05, n_samples)
X5 = np.random.normal(0, 100000, n_samples)

# Stack features
X = np.column_stack([X1, X2, X3, X4, X5])

# ------------------------------------------------------------
# TRUE UNDERLYING RELATIONSHIP
# ------------------------------------------------------------

noise = np.random.normal(0, 3, n_samples)

y = (
    15 * X1
    + 0.003 * X2
    + 60000 * X3
    + 10 * X4
    + 0.00015 * X5
    + noise
)

# ============================================================
# TRAIN / TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# ============================================================
# ALPHA SEARCH SPACE
# ============================================================

alphas = np.logspace(-2, 3, 100)

# ============================================================
# MODEL 1: WITHOUT NORMALISATION
# ============================================================

ridge_cv_raw = RidgeCV(alphas=alphas)

ridge_cv_raw.fit(X_train, y_train)

best_alpha_raw = ridge_cv_raw.alpha_

model_raw = Ridge(alpha=best_alpha_raw)

model_raw.fit(X_train, y_train)

y_pred_raw = model_raw.predict(X_test)

r2_raw = r2_score(y_test, y_pred_raw)

# ============================================================
# MODEL 2: WITH NORMALISATION
# ============================================================

ridge_cv_scaled = Pipeline([
    ("scaler", StandardScaler()),
    ("ridgecv", RidgeCV(alphas=alphas))
])

ridge_cv_scaled.fit(X_train, y_train)

best_alpha_scaled = ridge_cv_scaled.named_steps["ridgecv"].alpha_

model_scaled = Pipeline([
    ("scaler", StandardScaler()),
    ("ridge", Ridge(alpha=best_alpha_scaled))
])

model_scaled.fit(X_train, y_train)

y_pred_scaled = model_scaled.predict(X_test)

r2_scaled = r2_score(y_test, y_pred_scaled)

# ============================================================
# RESULTS
# ============================================================

print("=" * 70)
print("RIDGE REGRESSION COMPARISON")
print("=" * 70)

print(f"\nBest alpha WITHOUT normalisation: {best_alpha_raw:.4f}")
print(f"R² WITHOUT normalisation:         {r2_raw:.4f}")

print(f"\nBest alpha WITH normalisation:    {best_alpha_scaled:.4f}")
print(f"R² WITH normalisation:            {r2_scaled:.4f}")

# ============================================================
# COEFFICIENT COMPARISON
# ============================================================

feature_names = ["X1", "X2", "X3", "X4", "X5"]

coef_raw = pd.Series(
    model_raw.coef_,
    index=feature_names
)

coef_scaled = pd.Series(
    model_scaled.named_steps["ridge"].coef_,
    index=feature_names
)

print("\n" + "=" * 70)
print("COEFFICIENTS WITHOUT NORMALISATION")
print("=" * 70)

print(coef_raw)

print("\n" + "=" * 70)
print("COEFFICIENTS WITH NORMALISATION")
print("=" * 70)

print(coef_scaled)

# ============================================================
# VISUAL COMPARISON
# ============================================================

fig, axes = plt.subplots(1, 2, figsize=(15, 5))

# ------------------------------------------------------------
# WITHOUT SCALING
# ------------------------------------------------------------

visualizer1 = ResidualsPlot(
    model_raw,
    ax=axes[0]
)

visualizer1.fit(X_train, y_train)
visualizer1.score(X_test, y_test)

axes[0].set_title(
    f"Without Normalisation\n"
    f"R² = {r2_raw:.4f}\n"
    f"Best alpha = {best_alpha_raw:.4f}"
)

# ------------------------------------------------------------
# WITH SCALING
# ------------------------------------------------------------

visualizer2 = ResidualsPlot(
    model_scaled,
    ax=axes[1]
)

visualizer2.fit(X_train, y_train)
visualizer2.score(X_test, y_test)

axes[1].set_title(
    f"With Normalisation\n"
    f"R² = {r2_scaled:.4f}\n"
    f"Best alpha = {best_alpha_scaled:.4f}"
)

plt.tight_layout()
plt.show()





import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
from matplotlib import rcParams

# LaTeX-style formatting
rcParams['text.usetex'] = False
rcParams['font.family'] = 'serif'
rcParams['axes.labelsize'] = 13
rcParams['axes.titlesize'] = 13
rcParams['legend.fontsize'] = 12
rcParams['xtick.labelsize'] = 12
rcParams['ytick.labelsize'] = 12

# Set Seaborn theme
sns.set(style="whitegrid")

# ------------------------------------------------------------
# Generate skewed data with extreme outliers
# ------------------------------------------------------------
np.random.seed(42)
# Base skewed distribution (exponential) + large outliers
n = 500
skewed_base = np.random.exponential(scale=2.0, size=n)   # right‑skewed
outliers = np.random.uniform(30, 60, size=10)            # extreme values
data = np.concatenate([skewed_base, outliers])

# Log transform (add 1 to avoid log(0) – all data >=0)
data_log = np.log1p(data)   # log(1 + x)

# ------------------------------------------------------------
# 2×2 subplots
# ------------------------------------------------------------
fig, axes = plt.subplots(2, 2, figsize=(13, 10))

# --- Row 1: Original data (skewed + outliers) ---
# Histogram + KDE
sns.histplot(
    data, kde=True, stat="density", bins=40,
    color="red", edgecolor="black", alpha=0.7,
    label=r"\textbf{Original data}", ax=axes[0,0]
)
# Customize KDE line
for line in axes[0,0].lines:
    line.set_linestyle("--")
    line.set_color("teal")
    line.set_linewidth(2)
    line.set_label(r"\textbf{KDE}")
axes[0,0].set_title(r"\textbf{Original distribution (skewed + outliers)}")
axes[0,0].set_xlabel(r"\textbf{Value}")
axes[0,0].set_ylabel(r"\textbf{Density}")
axes[0,0].legend()
axes[0,0].grid(True, linestyle="--", linewidth=0.7, alpha=0.7)

# QQ‑plot (original)
stats.probplot(data, dist="norm", plot=axes[0,1])
axes[0,1].get_lines()[1].set_color('teal')          # fit line
axes[0,1].get_lines()[0].set_markerfacecolor("red") # points
axes[0,1].set_title(r"\textbf{Q-Q plot (original)}")
axes[0,1].set_xlabel(r"\textbf{Theoretical quantiles}")
axes[0,1].set_ylabel(r"\textbf{Sample quantiles}")
axes[0,1].legend(
    handles=[axes[0,1].get_lines()[0], axes[0,1].get_lines()[1]],
    labels=[r"\textbf{Data}", r"\textbf{Normal line}"],
    loc="best"
)
axes[0,1].grid(True, linestyle="--", linewidth=0.7, alpha=0.7)

# --- Row 2: Log‑transformed data ---
sns.histplot(
    data_log, kde=True, stat="density", bins=40,
    color="red", edgecolor="black", alpha=0.7,
    label=r"\textbf{Log‑transformed}", ax=axes[1,0]
)
for line in axes[1,0].lines:
    line.set_linestyle("--")
    line.set_color("teal")
    line.set_linewidth(2)
    line.set_label(r"\textbf{KDE}")
axes[1,0].set_title(r"\textbf{Log‑transformed distribution}")
axes[1,0].set_xlabel(r"\textbf{log(1 + x)}")
axes[1,0].set_ylabel(r"\textbf{Density}")
axes[1,0].legend()
axes[1,0].grid(True, linestyle="--", linewidth=0.7, alpha=0.7)

# QQ‑plot (log‑transformed)
stats.probplot(data_log, dist="norm", plot=axes[1,1])
axes[1,1].get_lines()[1].set_color('teal')
axes[1,1].get_lines()[0].set_markerfacecolor("red")
axes[1,1].set_title(r"\textbf{Q-Q plot (log‑transformed)}")
axes[1,1].set_xlabel(r"\textbf{Theoretical quantiles}")
axes[1,1].set_ylabel(r"\textbf{Sample quantiles}")
axes[1,1].legend(
    handles=[axes[1,1].get_lines()[0], axes[1,1].get_lines()[1]],
    labels=[r"\textbf{Data}", r"\textbf{Normal line}"],
    loc="best"
)
axes[1,1].grid(True, linestyle="--", linewidth=0.7, alpha=0.7)

plt.tight_layout()
plt.show()



import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
from matplotlib import rcParams

# ============================================================
# MATPLOTLIB SETTINGS
# ============================================================

rcParams['text.usetex'] = False
rcParams['font.family'] = 'serif'
rcParams['axes.labelsize'] = 13
rcParams['axes.titlesize'] = 13
rcParams['legend.fontsize'] = 12
rcParams['xtick.labelsize'] = 12
rcParams['ytick.labelsize'] = 12

sns.set(style="whitegrid")

# ============================================================
# GENERATE SKEWED DATA WITH OUTLIERS
# ============================================================

np.random.seed(42)

n = 500

skewed_base = np.random.exponential(
    scale=2.0,
    size=n
)

outliers = np.random.uniform(
    30,
    60,
    size=10
)

data = np.concatenate([skewed_base, outliers])

# ------------------------------------------------------------
# LOG TRANSFORMATION
# ------------------------------------------------------------

data_log = np.log1p(data)

# ============================================================
# HELPER FUNCTION
# ============================================================

def add_r2_annotation(ax, r):
    r2 = r ** 2

    ax.annotate(
        f'$R^2 = {r2:.4f}$',
        xy=(0.05, 0.90),
        xycoords='axes fraction',
        fontsize=12,
        bbox=dict(
            boxstyle="round,pad=0.3",
            facecolor="white",
            alpha=0.8
        )
    )

# ============================================================
# CREATE SUBPLOTS
# ============================================================

fig, axes = plt.subplots(
    2,
    2,
    figsize=(13, 10)
)

# ============================================================
# ROW 1 — ORIGINAL DATA
# ============================================================

# ------------------------------------------------------------
# HISTOGRAM + KDE
# ------------------------------------------------------------

sns.histplot(
    data,
    kde=True,
    stat="density",
    bins=40,
    color="red",
    edgecolor="black",
    alpha=0.7,
    label="Original data",
    ax=axes[0,0]
)

for line in axes[0,0].lines:
    line.set_linestyle("--")
    line.set_color("teal")
    line.set_linewidth(2)
    line.set_label("KDE")

axes[0,0].set_title(
    "Original distribution (skewed + outliers)"
)

axes[0,0].set_xlabel("Value")
axes[0,0].set_ylabel("Density")

axes[0,0].legend()

axes[0,0].grid(
    True,
    linestyle="--",
    linewidth=0.7,
    alpha=0.7
)

# ------------------------------------------------------------
# QQ-PLOT (ORIGINAL)
# ------------------------------------------------------------

(osm, osr), (slope, intercept, r) = stats.probplot(
    data,
    dist="norm",
    plot=axes[0,1]
)

axes[0,1].get_lines()[1].set_color("teal")

axes[0,1].get_lines()[0].set_markerfacecolor("red")

axes[0,1].set_title("Q-Q plot (original)")

axes[0,1].set_xlabel("Theoretical quantiles")
axes[0,1].set_ylabel("Sample quantiles")

axes[0,1].legend(
    handles=[
        axes[0,1].get_lines()[0],
        axes[0,1].get_lines()[1]
    ],
    labels=[
        "Data",
        "Normal line"
    ],
    loc="best"
)

axes[0,1].grid(
    True,
    linestyle="--",
    linewidth=0.7,
    alpha=0.7
)

add_r2_annotation(axes[0,1], r)

# ============================================================
# ROW 2 — LOG-TRANSFORMED DATA
# ============================================================

# ------------------------------------------------------------
# HISTOGRAM + KDE
# ------------------------------------------------------------

sns.histplot(
    data_log,
    kde=True,
    stat="density",
    bins=40,
    color="red",
    edgecolor="black",
    alpha=0.7,
    label="Log-transformed",
    ax=axes[1,0]
)

for line in axes[1,0].lines:
    line.set_linestyle("--")
    line.set_color("teal")
    line.set_linewidth(2)
    line.set_label("KDE")

axes[1,0].set_title(
    "Log-transformed distribution"
)

axes[1,0].set_xlabel("log(1 + x)")
axes[1,0].set_ylabel("Density")

axes[1,0].legend()

axes[1,0].grid(
    True,
    linestyle="--",
    linewidth=0.7,
    alpha=0.7
)

# ------------------------------------------------------------
# QQ-PLOT (LOG-TRANSFORMED)
# ------------------------------------------------------------

(osm_log, osr_log), (slope_log, intercept_log, r_log) = stats.probplot(
    data_log,
    dist="norm",
    plot=axes[1,1]
)

axes[1,1].get_lines()[1].set_color("teal")

axes[1,1].get_lines()[0].set_markerfacecolor("red")

axes[1,1].set_title("Q-Q plot (log-transformed)")

axes[1,1].set_xlabel("Theoretical quantiles")
axes[1,1].set_ylabel("Sample quantiles")

axes[1,1].legend(
    handles=[
        axes[1,1].get_lines()[0],
        axes[1,1].get_lines()[1]
    ],
    labels=[
        "Data",
        "Normal line"
    ],
    loc="best"
)

axes[1,1].grid(
    True,
    linestyle="--",
    linewidth=0.7,
    alpha=0.7
)

add_r2_annotation(axes[1,1], r_log)

# ============================================================
# FINAL LAYOUT
# ============================================================

plt.tight_layout()

plt.show()





import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
from scipy.signal import medfilt
from scipy.stats import norm
from matplotlib import rcParams

# ============================================================
# MATPLOTLIB SETTINGS (from first script)
# ============================================================
rcParams['text.usetex'] = False
rcParams['font.family'] = 'serif'
rcParams['axes.labelsize'] = 13
rcParams['axes.titlesize'] = 13
rcParams['legend.fontsize'] = 12
rcParams['xtick.labelsize'] = 12
rcParams['ytick.labelsize'] = 12
sns.set(style="whitegrid")

# ============================================================
# 1. GENERATE DATA (same as in first script)
# ============================================================
np.random.seed(42)
n = 500
skewed_base = np.random.exponential(scale=2.0, size=n)
outliers = np.random.uniform(30, 60, size=10)
raw_data = np.concatenate([skewed_base, outliers])
log_data = np.log1p(raw_data)          # log(1+x) transformation

# ============================================================
# 2. HYBRID OUTLIER DETECTION CLASS (from second script)
# ============================================================
class HybridOutlierDetection:
    def __init__(self, window_size, mad_multiplier=3.0):
        self.window_size = window_size
        self.mad_multiplier = mad_multiplier

    def bcp_analysis(self, time_series, prior='uniform'):
        cps = []
        start_idx = 0
        while start_idx < len(time_series):
            segment = time_series[start_idx:]
            if len(segment) < 3:
                break
            mean = np.mean(segment)
            std = np.std(segment)
            p_values = []
            for i in range(1, len(segment)):
                seg1 = segment[:i]
                seg2 = segment[i:]
                likelihood_seg1 = norm.logpdf(seg1, mean, std).sum()
                likelihood_seg2 = norm.logpdf(seg2, mean, std).sum()
                p = likelihood_seg1 + likelihood_seg2
                if prior == 'uniform':
                    prior_i = np.log(1 / (len(segment) - 1))
                else:
                    raise NotImplementedError
                p_values.append(p + prior_i)
            max_idx = np.argmax(p_values)
            if p_values[max_idx] > np.log(1 / len(segment)):
                cps.append(start_idx + max_idx)
                start_idx += max_idx + 1
            else:
                break
        return cps

    def iqr_outliers(self, time_series):
        q1, q3 = np.percentile(time_series, [25, 75])
        iqr = q3 - q1
        lower_bound = q1 - self.mad_multiplier * self.mad(time_series)
        upper_bound = q3 + self.mad_multiplier * self.mad(time_series)
        outliers = np.where((time_series < lower_bound) | (time_series > upper_bound))[0]
        return outliers.tolist()

    def mad(self, time_series):
        return np.median(np.abs(time_series - np.median(time_series)))

    def hampel_identifier(self, time_series, cps):
        outliers = []
        for i in range(len(cps) - 1):
            start_idx = cps[i]
            end_idx = cps[i + 1] if i + 1 < len(cps) else len(time_series)
            segment = time_series[start_idx:end_idx]
            median = np.median(segment)
            mad = np.median(np.abs(segment - median))
            threshold = self.mad_multiplier * mad
            for j in range(len(segment)):
                if np.abs(segment[j] - median) > threshold:
                    outliers.append(start_idx + j)
        return outliers

    def detect_outliers(self, time_series):
        iqr_out = self.iqr_outliers(time_series)
        cps = self.bcp_analysis(time_series)
        hampel_out = self.hampel_identifier(time_series, cps)
        return list(set(iqr_out + hampel_out))

    def correct_outliers(self, time_series, outliers):
        corrected = time_series.copy()
        for idx in outliers:
            ws = self.window_size
            start = max(0, idx - ws // 2)
            end = min(len(time_series), idx + ws // 2 + 1)
            corrected[idx] = medfilt(time_series[start:end], kernel_size=ws)[ws // 2]
        return corrected

# ============================================================
# 3. APPLY TO RAW DATA AND LOG-TRANSFORMED DATA
# ============================================================
detector = HybridOutlierDetection(window_size=5, mad_multiplier=2.0)

# Raw data
raw_outliers = detector.detect_outliers(raw_data)
raw_corrected = detector.correct_outliers(raw_data, raw_outliers)

# Log data
log_outliers = detector.detect_outliers(log_data)
log_corrected = detector.correct_outliers(log_data, log_outliers)

# ============================================================
# 4. VISUALISATION: ORIGINAL SIGNAL, OUTLIERS, CORRECTED
# ============================================================
fig, axes = plt.subplots(2, 3, figsize=(18, 10))

# Raw data row
axes[0,0].plot(raw_data, color='blue')
axes[0,0].set_title('Raw Data (original)')
axes[0,0].set_xlabel('Index')
axes[0,0].set_ylabel('Value')

axes[0,1].plot(raw_data, color='blue', label='Original')
axes[0,1].scatter(raw_outliers, raw_data[raw_outliers], color='red', label='Outliers')
axes[0,1].set_title('Raw Data + Detected Outliers')
axes[0,1].legend()

axes[0,2].plot(raw_corrected, color='green')
axes[0,2].set_title('Raw Data (corrected)')

# Log data row
axes[1,0].plot(log_data, color='blue')
axes[1,0].set_title('Log-transformed Data (original)')
axes[1,0].set_xlabel('Index')
axes[1,0].set_ylabel('log(1+x)')

axes[1,1].plot(log_data, color='blue', label='Original')
axes[1,1].scatter(log_outliers, log_data[log_outliers], color='red', label='Outliers')
axes[1,1].set_title('Log Data + Detected Outliers')
axes[1,1].legend()

axes[1,2].plot(log_corrected, color='green')
axes[1,2].set_title('Log Data (corrected)')

plt.suptitle('Hybrid Outlier Detection (BCP + IQR + Hampel)', fontsize=16)
plt.tight_layout()
plt.show()

# ============================================================
# 5. NORMALITY CHECK AFTER CORRECTION (Histogram + Q-Q)
# ============================================================
fig2, axes2 = plt.subplots(2, 2, figsize=(13, 10))

# Raw corrected
sns.histplot(raw_corrected, kde=True, stat='density', bins=40,
             color='red', edgecolor='black', alpha=0.7, ax=axes2[0,0])
axes2[0,0].set_title('Raw Data after Outlier Correction')
axes2[0,0].set_xlabel('Value')
axes2[0,0].grid(True, linestyle='--', alpha=0.7)

stats.probplot(raw_corrected, dist='norm', plot=axes2[0,1])
axes2[0,1].get_lines()[1].set_color('teal')
axes2[0,1].get_lines()[0].set_markerfacecolor('red')
axes2[0,1].set_title('Q-Q plot (raw corrected)')
axes2[0,1].grid(True, linestyle='--', alpha=0.7)

# Log corrected
sns.histplot(log_corrected, kde=True, stat='density', bins=40,
             color='red', edgecolor='black', alpha=0.7, ax=axes2[1,0])
axes2[1,0].set_title('Log Data after Outlier Correction')
axes2[1,0].set_xlabel('log(1+x)')
axes2[1,0].grid(True, linestyle='--', alpha=0.7)

stats.probplot(log_corrected, dist='norm', plot=axes2[1,1])
axes2[1,1].get_lines()[1].set_color('teal')
axes2[1,1].get_lines()[0].set_markerfacecolor('red')
axes2[1,1].set_title('Q-Q plot (log corrected)')
axes2[1,1].grid(True, linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

# Optional: print outlier counts
print(f"Raw data: {len(raw_outliers)} outliers detected")
print(f"Log data: {len(log_outliers)} outliers detected")



import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
from matplotlib import rcParams

# ============================================================
# SETTINGS
# ============================================================
rcParams.update({'font.family': 'serif', 'axes.labelsize': 13})
sns.set(style="whitegrid")
np.random.seed(42)

# ============================================================
# 1. GENERATE DATA
# ============================================================
n = 500
skewed_base = np.random.exponential(scale=2.0, size=n)
outliers = np.random.uniform(30, 60, size=10)
raw = np.concatenate([skewed_base, outliers])
log = np.log1p(raw)

# ============================================================
# 2. OUTLIER DETECTION & CORRECTION
# ============================================================
def detect_outliers_mad(data, threshold=2.5):
    """Return boolean mask of outliers using MAD with lower threshold."""
    median = np.median(data)
    mad = np.median(np.abs(data - median))
    if mad == 0:
        return np.zeros(len(data), dtype=bool)
    z_scores = 0.6745 * (data - median) / mad
    return np.abs(z_scores) > threshold

def correct_outliers_winsorize(data, outliers_mask, lower_percentile=1, upper_percentile=99):
    """Replace outliers with specified percentiles of the clean data."""
    corrected = data.copy()
    if not outliers_mask.any():
        return corrected
    clean = data[~outliers_mask]
    if len(clean) == 0:
        return corrected
    low_val = np.percentile(clean, lower_percentile)
    high_val = np.percentile(clean, upper_percentile)
    corrected[outliers_mask & (data < low_val)] = low_val
    corrected[outliers_mask & (data > high_val)] = high_val
    return corrected

# Detect outliers with different thresholds for raw and log
raw_outliers = detect_outliers_mad(raw, threshold=2.5)   # more sensitive
log_outliers = detect_outliers_mad(log, threshold=2.0)   # even more sensitive on log scale

# Correct (use tighter percentiles to force change)
raw_corrected = correct_outliers_winsorize(raw, raw_outliers, lower_percentile=5, upper_percentile=95)
log_corrected = correct_outliers_winsorize(log, log_outliers, lower_percentile=5, upper_percentile=95)

print(f"Raw outliers detected: {raw_outliers.sum()} (threshold=2.5 MAD)")
print(f"Log outliers detected: {log_outliers.sum()} (threshold=2.0 MAD)")

# ============================================================
# 3. VISUAL COMPARISON – BEFORE vs AFTER CORRECTION (only log scale shown)
# ============================================================
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Log original
axes[0].plot(log, color='blue', alpha=0.6)
axes[0].set_title(f'Log original (outliers: {log_outliers.sum()})')
axes[0].set_xlabel('Index')
axes[0].set_ylabel('log(1+x)')

# Log with outliers highlighted
axes[1].plot(log, color='blue', label='Original', alpha=0.6)
axes[1].scatter(np.where(log_outliers)[0], log[log_outliers], color='red', s=40, label='Detected outliers')
axes[1].set_title('Log data + detected outliers')
axes[1].legend()

# Log corrected
axes[2].plot(log_corrected, color='green', alpha=0.6)
axes[2].set_title('Log corrected (winsorized)')
axes[2].set_xlabel('Index')

plt.tight_layout()
plt.show()

# ============================================================
# 4. NORMALITY ASSESSMENT (Shapiro–Wilk + Q-Q plots)
# ============================================================
def shapiro_test(name, data):
    stat, p = stats.shapiro(data)
    print(f"{name:25} | W = {stat:.4f}, p = {p:.4e} -> {'Normal' if p > 0.05 else 'Not normal'}")

print("\n=== Shapiro–Wilk normality test ===\n")
shapiro_test("Raw original", raw)
shapiro_test("Raw corrected", raw_corrected)
shapiro_test("Log original", log)
shapiro_test("Log corrected", log_corrected)

# Q-Q plots before and after correction (log scale focus)
fig2, axes2 = plt.subplots(1, 2, figsize=(12, 5))

stats.probplot(log, dist="norm", plot=axes2[0])
axes2[0].set_title("Log original Q-Q plot")
axes2[0].get_lines()[1].set_color('red')
axes2[0].grid(True, linestyle='--', alpha=0.6)

stats.probplot(log_corrected, dist="norm", plot=axes2[1])
axes2[1].set_title("Log corrected Q-Q plot")
axes2[1].get_lines()[1].set_color('green')
axes2[1].grid(True, linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()

# ============================================================
# 5. HISTOGRAM COMPARISON (log scale)
# ============================================================
fig3, axes3 = plt.subplots(1, 2, figsize=(12, 5))

sns.histplot(log, kde=True, stat='density', bins=40, color='blue', alpha=0.6, ax=axes3[0])
axes3[0].set_title("Log original density")
axes3[0].grid(True, linestyle='--', alpha=0.6)


sns.histplot(log_corrected, kde=True, stat='density', bins=40, color='green', alpha=0.6, ax=axes3[1])
axes3[1].set_title("Log corrected density")
axes3[1].grid(True, linestyle='--', alpha=0.6)


plt.tight_layout()
plt.show()

